=== bcgov/FIT_opendatadownloader/source_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/bcgov/fit_changedetector/main/source.schema.json",
    "title": "Data source schema",
    "description": "Definition of data sources for output layers",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "out_layer": {
                "description": "Name of output dataset, only parks and roads are currently supported",
                "type": "string",
                "enum": [
                    "roads",
                    "parks"
                    ]
            },
            "source": {
                "description": "url/file path to a file based source readable by GDAL/OGR or a Esri REST layer endpoint URL",
                "type": "string"
            },
            "protocol": {
                "description": "Resource type for the source, one of http / esri / bcgw",
                "type": "string",
                "enum": [
                    "http",
                    "esri",
                    "bcgw"
                ]
            },
            "fields": {
                "description": "List of source field(s) to retain in the download",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "schedule": {
                "description": "Download frequency (D=Daily, W=Weekly, M=Monthly, Q=Quarterly, A=Annualy",
                "type": "string",
                "enum": [
                    "D",
                    "W",
                    "M",
                    "Q",
                    "A"
                ]
            },
            "source_layer": {
                "description": "Name of layer to use within source, default is first layer in file",
                "type": "string"
            },
            "query": {
                "description": "Query to subset data in source/layer - ECQL for BCGW sources, OGR SQL for files",
                "type": ["string", "null"]
            },
            "primary_key": {
                "description": "List of source field(s) used as primary key, must be a subset of `fields`",
                "type": "array",
                "items": {
                    "type": ["string", "null"]
                }
            },
            "metadata_url": {
                "description": "Link to source metadata, where available",
                "type": ["string", "null"]
            }
        },
        "required": [
            "out_layer",
            "source",
            "protocol",
            "fields",
            "schedule"
        ]
    }
}

=== bcgov/FIT_opendatadownloader/sources/MVRD/surrey.json
[
    {
        "out_layer": "parks",
        "source": "https://cosmos.surrey.ca/geo_ref/Images/OpenDataArchives/parks_GDB.zip",
        "source_layer": "parks",
        "protocol": "http",
        "fields": [
            "FACILITYID",
            "DESCRIPTION",
            "LOCATION",
            "PARK_NAME",
            "STATUS"
        ],
        "primary_key": ["FACILITYID"],
        "schedule": "Q"
    }
]

=== bcgov/FIT_opendatadownloader/sources/FFGRD/prince_george.json
[
    {
        "out_layer": "roads",
        "metadata_url": null,
        "source": "https://services2.arcgis.com/CnkB6jCzAsyli34z/arcgis/rest/services/OpenData_RoadTraffic/FeatureServer/4",
        "protocol": "esri",
        "query": null,
        "fields": [
            "AssetID",
            "Location",
            "StrName",
            "StrType",
            "SurfaceMaterial",
            "NumberofLanes",
            "StrPrefix",
            "StrSuffix",
            "FullName",
            "LF_Addr",
            "RF_Addr",
            "LT_Addr",
            "RT_Addr",
            "SubType_TEXT",
            "DGRoute",
            "SpeedLimit"
        ],
        "primary_key": ["AssetID"],
        "schedule": "Q"
    }
]

=== bcgov/FIT_opendatadownloader/sources/CORD/kelowna.json
[
  {
    "out_layer": "roads",
    "source": "https://geo.kelowna.ca/arcgis/rest/services/OpenData/MapServer/5",
    "protocol": "esri",
    "fields": [
      "road_id",
      "status",
      "roadmst_name",
      "road_class",
      "high_address",
      "low_address",
      "address_range",
      "odd_side",
      "SHAPE.STLength()"
    ],
    "schedule": "Q",
    "primary_key": [
      "STREETNAME",
      "SHAPE.STLength()"
    ]
  },
  {
    "out_layer": "parks",
    "source": "https://geo.kelowna.ca/arcgis/rest/services/OpenData/MapServer/22",
    "source_layer": "Parks",
    "protocol": "esri",
    "fields": [
      "Name",
      "Size",
      "Address",
      "Class",
      "SHAPE.STArea()"
    ],
    "primary_key": [
      "Name",
      "Size"
    ],
    "schedule": "Q"
  }
]

=== bcgov/FIT_opendatadownloader/sources/_TEST/test.json
[
  {
    "out_layer": "parks",
    "source": "https://raw.githubusercontent.com/bcgov/FIT_changedetector/refs/heads/main/tests/data/parks_a.geojson",
    "source_layer": "parks",
    "protocol": "http",
    "fields": [
      "id",
      "park_name",
      "parkclasscode"
    ],
    "primary_key": [
      "id"
    ],
    "schedule": "Q"
  }
]

=== bcgov/FIT_opendatadownloader/sources/SCRD/SCRD.json
[
  {
    "out_layer": "roads",
    "source": "https://maps.scrd.ca/arcgis/rest/services/OpenData/Transportation_Roads/MapServer/0",
    "protocol": "esri",
    "fields": [
      "STREETNAME",
      "RD_CLASS",
      "RD_SURFACE",
      "SHAPE.STLength()"
    ],
    "schedule": "Q",
    "primary_key": [
      "STREETNAME",
      "SHAPE.STLength()"
    ]
  },
  {
    "out_layer": "parks",
    "source": "https://maps.scrd.ca/arcgis/rest/services/OpenData/Parks_TagGroup/MapServer/2",
    "source_layer": "Parks",
    "protocol": "esri",
    "fields": [
      "PARK_NAME",
      "PRK_TYPE",
      "SHAPE_STArea"
    ],
    "primary_key": [
      "NAME",
      "SHAPE_STArea"
    ],
    "schedule": "Q"
  }
]

=== bcgov/FIT_opendatadownloader/sources/FVRD/chilliwack.json
[
  {
    "out_layer": "roads",
    "source": "/vsizip//vsicurl/https://opendata.chilliwack.com/shp/Roads_SHP.zip",
    "source_layer": "Roads",
    "protocol": "http",
    "fields": [
      "NAME",
      "TYPE",
      "SURFACE",
      "DIRECTION",
      "AssetID"
    ],
    "schedule": "Q",
    "primary_key": [
      "AssetID"
    ]
  },
  {
    "out_layer": "parks",
    "source": "/vsizip//vsicurl/https://opendata.chilliwack.com/shp/Parks_SHP.zip",
    "source_layer": "Parks",
    "protocol": "http",
    "fields": [
      "NAME"
    ],
    "schedule": "Q"
  }
]

=== bcgov/FIT_opendatadownloader/sources/NRD/nanaimo.json
[
  {
    "out_layer": "parks",
    "source": "/vsizip//vsicurl/https://www.nanaimo.ca/GISFiles/shp/Parks.zip",
    "source_layer": "PARKS",
    "protocol": "http",
    "fields": [
      "PARKNAME",
      "PARKADDRESS",
      "CITYOWNED",
      "GLOBALID",
      "PARKID"
    ],
    "primary_key": [
      "PARKID"
    ],
    "schedule": "Q"
  },
  {
    "out_layer": "roads",
    "source": "/vsizip//vsicurl/https://www.nanaimo.ca/GISFiles/shp/RoadNetwork.zip",
    "source_layer": "ROAD_CENTERLINES",
    "protocol": "http",
    "fields": [
      "STREETNAME",
      "CLASS",
      "SURFACE",
      "GID"
    ],
    "schedule": "Q",
    "primary_key": [
      "GID"
    ]
  }
]

=== bcgov/FIT_opendatadownloader/sources/MVRD/burnaby.json
[
  {
    "out_layer": "roads",
    "source": "https://gis.burnaby.ca/arcgis/rest/services/OpenData/OpenData5/MapServer/8",
    "protocol": "esri",
    "fields": [
      "COMPKEY",
      "UNITID",
      "HIADDRESS",
      "LOADDRESS",
      "STREETNAMEC",
      "TRUCKROUTE"
    ],
    "schedule": "Q",
    "primary_key": [
      "COMPKEY"
    ]
  },
  {
    "out_layer": "parks",
    "source": "https://gis.burnaby.ca/arcgis/rest/services/OpenData/OpenData1/MapServer/6",
    "source_layer": "Parks",
    "protocol": "esri",
    "fields": [
      "NAME",
      "CLASSIFICATION",
      "OWNERSHIP",
      "PARK_STATUS"
    ],
    "schedule": "Q"
  }
]
