=== bcgov/FIT_opendatadownloader/source_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/bcgov/fit_changedetector/main/source.schema.json",
    "title": "Data source schema",
    "description": "Definition of data sources for output layers",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "out_layer": {
                "description": "Name of output dataset, only parks and roads are currently supported",
                "type": "string",
                "enum": [
                    "roads",
                    "parks"
                    ]
            },
            "source": {
                "description": "url/file path to a file based source readable by GDAL/OGR or a Esri REST layer endpoint URL",
                "type": "string"
            },
            "protocol": {
                "description": "Resource type for the source, one of http / esri / bcgw",
                "type": "string",
                "enum": [
                    "http",
                    "esri",
                    "bcgw"
                ]
            },
            "fields": {
                "description": "List of source field(s) to retain in the download",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "schedule": {
                "description": "Download frequency (D=Daily, W=Weekly, M=Monthly, Q=Quarterly, A=Annualy",
                "type": "string",
                "enum": [
                    "D",
                    "W",
                    "M",
                    "Q",
                    "A"
                ]
            },
            "source_layer": {
                "description": "Name of layer to use within source, default is first layer in file",
                "type": "string"
            },
            "query": {
                "description": "Query to subset data in source/layer - ECQL for BCGW sources, OGR SQL for files",
                "type": ["string", "null"]
            },
            "primary_key": {
                "description": "List of source field(s) used as primary key, must be a subset of `fields`",
                "type": "array",
                "items": {
                    "type": ["string", "null"]
                }
            },
            "metadata_url": {
                "description": "Link to source metadata, where available",
                "type": ["string", "null"]
            }
        },
        "required": [
            "out_layer",
            "source",
            "protocol",
            "fields",
            "schedule"
        ]
    }
}

=== bcgov/FIT_opendatadownloader/sources/TNRD/kamloops.json
[
  {
    "out_layer": "roads",
    "source": "https://maps.kamloops.ca/arcgis/rest/services/OpenData/OpenDataPlanimetric/MapServer/28",
    "protocol": "esri",
    "fields": [
      "FACILITYID",
      "STREETNAME",
      "ALTERNATENAME",
      "RANGETYPE",
      "BEGINLEFT",
      "BEGINRIGHT",
      "ENDLEFT",
      "ENDRIGHT",
      "TRAFFICDIRECTION",
      "ASSETSTATUS"
    ],
    "schedule": "Q",
    "primary_key": [
      "FACILITYID"
    ]
  },
  {
    "out_layer": "parks",
    "source": "/vsizip//vsicurl/https://maps.kamloops.ca/OpenData/zipfiles/ParksSHP.zip",
    "source_layer": "Park",
    "protocol": "http",
    "fields": [
      "NAME",
      "ADDRESS",
      "SITETYPE",
      "CLASSIFICA"
    ],
    "schedule": "Q"
  }
]

=== bcgov/FIT_opendatadownloader/sources/STRD/strd.json
[
  {
    "out_layer": "parks",
    "source": "https://services1.arcgis.com/Uj11SaUIGBo5JYFY/arcgis/rest/services/ParkBeachAccess/FeatureServer/1",
    "source_layer": "PARKS",
    "protocol": "esri",
    "fields": [
      "PARK",
      "STATUS",
      "TENURE"
    ],
    "primary_key": [
      "PARK",
      "TENURE"
    ],
    "schedule": "Q"
  }
]

=== bcgov/FIT_opendatadownloader/sources/MVRD/coquitlam.json
[
         {
            "out_layer": "parks",
            "metadata_url": null,
            "source": "https://coquitlam-spatial.s3.us-west-2.amazonaws.com/PRC/GDB/Coquitlam_Parks_GDB.zip",
            "source_layer": "parks",
            "protocol": "http",
            "query": null,
            "fields": [
                "PARKNAME",
                "ADDRESS",
                "PARKTYPE",
                "OWNERSHIP",
                "AREA_ACRES",
                "PARK_LEVEL"
            ],
            "primary_key": ["PARKNAME", "AREA_ACRES"],
            "schedule": "Q"
        },
        {
            "out_layer": "roads",
            "metadata_url": null,
            "source": "https://coquitlam-spatial.s3.us-west-2.amazonaws.com/Transportation/GDB/Coquitlam_Transportation_GDB.zip",
            "source_layer": "roads",
            "protocol": "http",
            "query": null,
            "fields": [
                "STATUS",
                "CLASS",
                "LEFTBEGIN",
                "LEFTEND",
                "RIGHTBEGIN",
                "RIGHTEND",
                "TRUCKROUTE",
                "ROADNAME",
                "ROADTYPE",
                "FULLNAME"
            ],
            "primary_key": ["FULLNAME"],
            "schedule": "Q"
        }
]

=== bcgov/FIT_opendatadownloader/sources/MVRD/langley.json
[
    {
        "out_layer": "roads",
        "source": "/vsizip/{/vsicurl/https://governmentofbc.maps.arcgis.com/sharing/rest/content/items/4bba119c2e9042d683cc9378fb1e836e/data}/CoL_TransportationNetwork Jan 3 2024.gdb",
        "source_layer": "TRN_ROADS",
        "protocol": "http",
        "fields": [
            "GISLINK",
            "NAME",
            "CLASSIFICATION",
            "OWNER",
            "FROM_LOCATION",
            "TO_LOCATION"
        ],
        "primary_key": ["GISLINK"],
        "schedule": "Q"
    }
]

=== bcgov/FIT_opendatadownloader/sources/CAPRD/victoria.json
[
  {
    "out_layer": "parks",
    "source": "https://maps.victoria.ca/server/rest/services/OpenData/OpenData_Parks/MapServer/50",
    "source_layer": "parks",
    "protocol": "esri",
    "fields": [
      "Park_Name",
      "ParkClassCode",
      "SHAPE_Area"
    ],
    "primary_key": [
      "Park_Name"
    ],
    "schedule": "Q"
  },
  {
    "out_layer": "roads",
    "source": "https://maps.victoria.ca/server/rest/services/OpenData/OpenData_Transportation/MapServer/25",
    "protocol": "esri",
    "fields": [
      "AddrType_L",
      "AddrType_R",
      "Class",
      "From_Left",
      "From_Right",
      "ToLeft",
      "ToRight",
      "StreetName",
      "AliasName",
      "StreetSegmentID"
    ],
    "schedule": "Q",
    "primary_key": [
      "StreetSegmentID"
    ]
  }
]
